### ISSUE TITLE
Datasets with different names to those in the scripts

### ISSUE THREAD

**Issue by sago2693** [Media-Bias-Group/Media-Bias-Identification-Benchmark#1]
Hi,
While completing the datasets for the full evaluation I came across the following issues:

1. UsVsThem's author sends 3 files:
UsVsThem_train_public.csv
UsVsThem_test_public.csv
UsVsThem_valid_public.csv
but the script expects: Reddit_dataset.xsc
2. bignews expects: 
   - BIGNEWSBLN_train_center.json
   - BIGNEWSBLN_train_left.json
   - BIGNEWSBLN_train_right.json
 but these are the datasets given
![imagen](https://github.com/Media-Bias-Group/MBIB/assets/56797497/91a67a86-6eb7-4f69-891a-deb46753d6a1)
Are there extra processing steps for these datasets?

**Comment by horychtom** [comment]
Hi,
As we don't have access to the source of the closed datasets, the author may do arbitrary changes to the format which make our scripts outdated. However, each dataset is processed with the  `process.py` script in the according directory  only. Therefore you can adjust this script for the new format. Feel free to make a merge request with the change.

For the UsVsThem dataset, you will neeed to adjust the script. For the BigNews I noticed that the authors added more versions, we are working with the version called BIGNEWSBLN. Therefore if you download this choice as seen below, the script will run as intended. Thank you for pointing it out, I changed the instructions in the BigNews directory.

![image](https://github.com/Media-Bias-Group/MBIB/assets/67648067/a5fe623e-4fc3-47f3-a3c9-3f90695218b5)
